### ISSUE TITLE
Request: allow action sequences that don't connect frames

### ISSUE THREAD

**Issue by mckinziebrandon** [google/sling#103]
I just solved an issue I'd been having that was resulting in the following error from `trainer_lib.run_training` (dragnn), via a call to `train.sh` with my own corpus:

```
InvalidArgumentError (see above for traceback): indices[0] = 0 is not in [0, 0)
	 [[Node: train-ff/Adam/update_ff/fixed_embedding_matrix_1/ScatterAdd = ScatterAdd[T=DT_FLOAT, Tindices=DT_INT64, _class=["loc:@ff/fixed_embedding_matrix_1"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ff/fixed_embedding_matrix_1/Adam, train-ff/Adam/update_ff/fixed_embedding_matrix_1/Unique, train-ff/Adam/update_ff/fixed_embedding_matrix_1/mul_1, ^train-ff/Adam/update_ff/fixed_embedding_matrix_1/Assign)]]
```
This puzzled me, because I had run `train.sh` without issues on a toy training dataset I made in the same way. After a couple days of scratching my head, I found the solution and, in my opinion, this seems like a bug. 

**Root cause of my problem**: I had SLING documents in my corpus that were essentially just named entity extraction labels (in addition to the doc tokens etc) -- documents with frames that only referenced some portion of the text, **but did not reference other frames**. For example:

```cpp
Builder personBuilder(doc->store());
personBuilder.AddIsA("/my/schema/person");
Frame personFrame = personBuilder.Create();
doc->AddSpan(0, 1)->Evoke(personFrame);
doc->Update();
``` 

**Solution**: I just need to have at least one frame that has a slot whose value is another frame. I've tried many variations of this and that's always what fixes the error. To continue with the example above, if I then make another frame with a slot value referencing the `personFrame`, all runs fine:

```cpp
Builder personBuilder(doc->store());
personBuilder.AddIsA("/my/schema/person");
Frame personFrame = personBuilder.Create();
doc->AddSpan(0, 1)->Evoke(personFrame);

Builder someBuilder(doc->store());
someBuilder.AddIsA("/my/schema/anotherthing");
someBuilder.Add("/my/schema/anotherthing/source", personFrame);
Frame someFrame = someBuilder.Create();
doc->AddSpan(1, 2)->Evoke(someFrame);

doc->Update();
```

So, my question is: is this intentional? I didn't see anything that indicated one _must_ have at least one connection from one frame to another. Interesting in hearing your thoughts. Thanks!

------------------------

More complete error output of `train.sh` (again, due to the `trainer_lib.run_training` call in `train.py`):

```
INFO:tensorflow:Training schedule defined!
INFO:tensorflow:Starting training...
2017-12-04 13:40:38.829931: I third_party/syntaxnet/dragnn/core/ops/dragnn_op_kernels.cc:78] Creating new ComputeSessionPool in container handle: shared
I1204 13:40:38.867660 30572 sempar-component.cc:58] lr_lstm: loaded 4753 words
I1204 13:40:38.867676 30572 sempar-component.cc:59] lr_lstm: loaded 0 prefixes
I1204 13:40:38.867679 30572 sempar-component.cc:60] lr_lstm: loaded 1663 suffixes
I1204 13:40:38.867681 30572 sempar-component.cc:62] Lexicon OOV: 0
I1204 13:40:38.867702 30572 sempar-component.cc:63] Lexicon normalize digits: 1
I1204 13:40:38.902065 30572 sempar-component.cc:58] rl_lstm: loaded 4753 words
I1204 13:40:38.902081 30572 sempar-component.cc:59] rl_lstm: loaded 0 prefixes
I1204 13:40:38.902101 30572 sempar-component.cc:60] rl_lstm: loaded 1663 suffixes
I1204 13:40:38.902102 30572 sempar-component.cc:62] Lexicon OOV: 0
I1204 13:40:38.902104 30572 sempar-component.cc:63] Lexicon normalize digits: 1
I1204 13:40:38.936980 30572 sempar-component.cc:58] ff: loaded 0 words
I1204 13:40:38.936996 30572 sempar-component.cc:59] ff: loaded 0 prefixes
I1204 13:40:38.937017 30572 sempar-component.cc:60] ff: loaded 0 suffixes
Traceback (most recent call last):
  File "nlp/parser/tools/train.py", line 245, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "nlp/parser/tools/train.py", line 232, in main
    checkpoint_filename=checkpoint_path)
  File "third_party/syntaxnet/dragnn/python/trainer_lib.py", line 119, in run_training
    sess, trainers[target_idx], train_corpus, batch_size)
  File "third_party/syntaxnet/dragnn/python/trainer_lib.py", line 60, in run_training_step
    feed_dict={trainer['input_batch']: batch})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 0 is not in [0, 0)
	 [[Node: train-ff/Adam/update_ff/fixed_embedding_matrix_1/ScatterAdd = ScatterAdd[T=DT_FLOAT, Tindices=DT_INT64, _class=["loc:@ff/fixed_embedding_matrix_1"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ff/fixed_embedding_matrix_1/Adam, train-ff/Adam/update_ff/fixed_embedding_matrix_1/Unique, train-ff/Adam/update_ff/fixed_embedding_matrix_1/mul_1, ^train-ff/Adam/update_ff/fixed_embedding_matrix_1/Assign)]]

Caused by op u'train-ff/Adam/update_ff/fixed_embedding_matrix_1/ScatterAdd', defined at:
  File "nlp/parser/tools/train.py", line 245, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "nlp/parser/tools/train.py", line 176, in main
    trainers += [builder.add_training_from_config(target)]
  File "third_party/syntaxnet/dragnn/python/graph_builder.py", line 482, in add_training_from_config
    **kwargs)
  File "third_party/syntaxnet/dragnn/python/graph_builder.py", line 350, in build_training
    clipped_gradients, global_step=self.master_vars['step'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 456, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 102, in update_op
    return optimizer._apply_sparse_duplicate_indices(g, self._v)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 654, in _apply_sparse_duplicate_indices
    return self._apply_sparse(gradient_no_duplicate_indices, var)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 197, in _apply_sparse
    lambda x, i, v: state_ops.scatter_add(  # pylint: disable=g-long-lambda
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 181, in _apply_sparse_shared
    m_t = scatter_add(m, indices, m_scaled_g_values)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 198, in <lambda>
    x, i, v, use_locking=self._use_locking))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 210, in scatter_add
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[0] = 0 is not in [0, 0)
	 [[Node: train-ff/Adam/update_ff/fixed_embedding_matrix_1/ScatterAdd = ScatterAdd[T=DT_FLOAT, Tindices=DT_INT64, _class=["loc:@ff/fixed_embedding_matrix_1"], use_locking=true, _device="/job:localhost/replica:0/task:0/cpu:0"](ff/fixed_embedding_matrix_1/Adam, train-ff/Adam/update_ff/fixed_embedding_matrix_1/Unique, train-ff/Adam/update_ff/fixed_embedding_matrix_1/mul_1, ^train-ff/Adam/update_ff/fixed_embedding_matrix_1/Assign)]]

2017-12-04 13:40:39.153166: I third_party/syntaxnet/dragnn/core/compute_session_pool.cc:55] Destroying pool: total number of sessions created = 1
2017-12-04 13:40:39.153191: W third_party/syntaxnet/dragnn/core/compute_session_pool.cc:58] Destroying pool: number of unreturned sessions = 1

```

**Comment by ringgaard** [comment]
We might have an implicit assumption that all frames have a type, i.e. every frame has an isa: slot. Does it work if you keep the `someBuilder.AddIsA(...)` but remove `someBuilder.Add(...)`?

**Comment by mckinziebrandon** [comment]
Well, notice that in my first example snippet (the one that does not work), there is an `AddIsA` call. Also, it may be helpful to users if implicit assumptions are mentioned somewhere in the docs, primarily because the associated errors are rather far downstream (within dragnn itself) when violated, which can make for difficult debugging.

I did try your suggestion, and removing `someBuilder.add(...)` from the second (working) snippet does indeed cause it to crash with the same error.

My best guess is that somewhere in the masterspec or perhaps `sempar.so` library there is an assumption that each document will have more than just SHIFT and STOP as its action set.

**Comment by rahul1980** [comment]
Can you post the generated master_spec file?
If none of your documents have inter-frame links, then I suspect the following fragment of your spec would have zero-vocab features (in bold below). Can you please confirm this?

  fixed_feature {
    name: "in-roles"
    fml: "in-roles 5"
    embedding_dim: 16
    **vocabulary_size: 0**
    size: 32
  }
  fixed_feature {
    name: "out-roles"
    fml: "out-roles 5"
    embedding_dim: 16
    **vocabulary_size: 0**
    size: 32
  }
  fixed_feature {
    name: "labeled-roles"
    fml: "labeled-roles 5"
    embedding_dim: 16
    **vocabulary_size: 0**
    size: 32
  }
  fixed_feature {
    name: "unlabeled-roles"
    fml: "unlabeled-roles 5"
    embedding_dim: 16
    **vocabulary_size: 0**
    size: 32
  }

This could explain the index out of bounds error you see. If so, then this is definitely a bug. If we have zero vocab features, then we should disable that feature altogether in the spec.

**Comment by rahul1980** [comment]
Also, if you indeed see the spec as above, then can you try disabling the four roles features (just delete them from master_spec), and run train.sh with --train_only (this will not regenerate the spec) ?

**Comment by mckinziebrandon** [comment]
Good catch! That appears to be the culprit. Also, your suggestion to remove the roles and run the script with `--train_only` also indeed fixes the error, allowing me to train on it. Awesome job! 

The generated master spec is below:

```
component {
  name: "lr_lstm"
  transition_system {
    registered_name: "shift-only"
    parameters {
      key: "left_to_right"
      value: "true"
    }
    parameters {
      key: "lexicon_normalize_digits"
      value: "true"
    }
    parameters {
      key: "lexicon_oov"
      value: "0"
    }
  }
  resource {
    name: "commons"
    part {
      file_pattern: "/home/brandon/Documents/Forge/resources/sling/scratch/data/forge_commons"
    }
  }
  resource {
    name: "word-vocab"
    part {
      file_pattern: "scratch/out/word-vocab"
    }
  }
  resource {
    name: "suffix-table"
    part {
      file_pattern: "scratch/out/suffix-table"
    }
  }
  fixed_feature {
    name: "words"
    fml: "word"
    embedding_dim: 32
    vocabulary_size: 6
    size: 1
  }
  fixed_feature {
    name: "suffix"
    fml: "suffix"
    embedding_dim: 16
    vocabulary_size: 10
    size: 3
  }
  fixed_feature {
    name: "capitalization"
    fml: "capitalization"
    embedding_dim: 8
    vocabulary_size: 5
    size: 1
  }
  fixed_feature {
    name: "hyphen"
    fml: "hyphen"
    embedding_dim: 8
    vocabulary_size: 2
    size: 1
  }
  fixed_feature {
    name: "punctuation"
    fml: "punctuation"
    embedding_dim: 8
    vocabulary_size: 3
    size: 1
  }
  fixed_feature {
    name: "quote"
    fml: "quote"
    embedding_dim: 8
    vocabulary_size: 4
    size: 1
  }
  fixed_feature {
    name: "digit"
    fml: "digit"
    embedding_dim: 8
    vocabulary_size: 3
    size: 1
  }
  network_unit {
    registered_name: "LSTMNetwork"
    parameters {
      key: "hidden_layer_sizes"
      value: "256"
    }
  }
  backend {
    registered_name: "SemparComponent"
  }
  num_actions: 1
  component_builder {
    registered_name: "DynamicComponentBuilder"
  }
}
component {
  name: "rl_lstm"
  transition_system {
    registered_name: "shift-only"
    parameters {
      key: "left_to_right"
      value: "false"
    }
    parameters {
      key: "lexicon_normalize_digits"
      value: "true"
    }
    parameters {
      key: "lexicon_oov"
      value: "0"
    }
  }
  resource {
    name: "commons"
    part {
      file_pattern: "/home/brandon/Documents/Forge/resources/sling/scratch/data/forge_commons"
    }
  }
  resource {
    name: "word-vocab"
    part {
      file_pattern: "scratch/out/word-vocab"
    }
  }
  resource {
    name: "suffix-table"
    part {
      file_pattern: "scratch/out/suffix-table"
    }
  }
  fixed_feature {
    name: "words"
    fml: "word"
    embedding_dim: 32
    vocabulary_size: 6
    size: 1
  }
  fixed_feature {
    name: "suffix"
    fml: "suffix"
    embedding_dim: 16
    vocabulary_size: 10
    size: 3
  }
  fixed_feature {
    name: "capitalization"
    fml: "capitalization"
    embedding_dim: 8
    vocabulary_size: 5
    size: 1
  }
  fixed_feature {
    name: "hyphen"
    fml: "hyphen"
    embedding_dim: 8
    vocabulary_size: 2
    size: 1
  }
  fixed_feature {
    name: "punctuation"
    fml: "punctuation"
    embedding_dim: 8
    vocabulary_size: 3
    size: 1
  }
  fixed_feature {
    name: "quote"
    fml: "quote"
    embedding_dim: 8
    vocabulary_size: 4
    size: 1
  }
  fixed_feature {
    name: "digit"
    fml: "digit"
    embedding_dim: 8
    vocabulary_size: 3
    size: 1
  }
  network_unit {
    registered_name: "LSTMNetwork"
    parameters {
      key: "hidden_layer_sizes"
      value: "256"
    }
  }
  backend {
    registered_name: "SemparComponent"
  }
  num_actions: 1
  component_builder {
    registered_name: "DynamicComponentBuilder"
  }
}
component {
  name: "ff"
  transition_system {
    registered_name: "sempar"
  }
  resource {
    name: "commons"
    part {
      file_pattern: "/home/brandon/Documents/Forge/resources/sling/scratch/data/forge_commons"
    }
  }
  resource {
    name: "action-table"
    part {
      file_pattern: "scratch/out/table"
    }
  }
  fixed_feature {
    name: "in-roles"
    fml: "in-roles 5"
    embedding_dim: 16
    vocabulary_size: 0
    size: 32
  }
  fixed_feature {
    name: "out-roles"
    fml: "out-roles 5"
    embedding_dim: 16
    vocabulary_size: 0
    size: 32
  }
  fixed_feature {
    name: "labeled-roles"
    fml: "labeled-roles 5"
    embedding_dim: 16
    vocabulary_size: 0
    size: 32
  }
  fixed_feature {
    name: "unlabeled-roles"
    fml: "unlabeled-roles 5"
    embedding_dim: 16
    vocabulary_size: 25
    size: 32
  }
  linked_feature {
    name: "frame-creation-steps"
    fml: "frame-creation"
    embedding_dim: 64
    size: 5
    source_component: "ff"
    source_translator: "identity"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "frame-focus-steps"
    fml: "frame-focus"
    embedding_dim: 64
    size: 5
    source_component: "ff"
    source_translator: "identity"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "frame-end-lr"
    fml: "frame-end"
    embedding_dim: 32
    size: 5
    source_component: "lr_lstm"
    source_translator: "identity"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "frame-end-rl"
    fml: "frame-end"
    embedding_dim: 32
    size: 5
    source_component: "rl_lstm"
    source_translator: "reverse-token"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "history"
    fml: "history"
    embedding_dim: 64
    size: 4
    source_component: "ff"
    source_translator: "history"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "lr"
    fml: "focus"
    embedding_dim: 32
    size: 1
    source_component: "lr_lstm"
    source_translator: "identity"
    source_layer: "layer_0"
  }
  linked_feature {
    name: "rl"
    fml: "focus"
    embedding_dim: 32
    size: 1
    source_component: "rl_lstm"
    source_translator: "reverse-token"
    source_layer: "layer_0"
  }
  network_unit {
    registered_name: "FeedForwardNetwork"
    parameters {
      key: "hidden_layer_sizes"
      value: "128"
    }
  }
  backend {
    registered_name: "SemparComponent"
  }
  num_actions: 3
  component_builder {
    registered_name: "DynamicComponentBuilder"
  }
}

```
