### ISSUE TITLE
ImportError: No module named download

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#220]
Hi there,
I am new to this project. Just followed the install and build instructions.  The  download.py is in place but still import fails
![sling](https://user-images.githubusercontent.com/55606/43872199-6bf76022-9b4e-11e8-8a8e-a9efb6399b87.PNG)

(python2) lenyabloko@cloudshell:~/sling (compact-haiku-176904)$ ./run.sh --help                             
Traceback (most recent call last):
  File "python/run.py", line 22, in <module>
    import sling.task.download as download
ImportError: No module named download

**Comment by ringgaard** [comment]
Did you add the link described in the install guide?
```
sudo ln -s $(realpath python) /usr/lib/python2.7/dist-packages/sling
```

**Comment by lenyabloko** [comment]
Yes. IWhat am I dong  wrong?

>>> os.path.realpath('python')
'/home/lenyabloko/sling/python'
>>>
(python2) lenyabloko@cloudshell:~/sling (compact-haiku-176904)$ sudo ln -s /home/lenyabloko/sling/python /usr/lib/python2.7/dist-packages/sling
(python2) lenyabloko@cloudshell:~/sling (compact-haiku-176904)$ ./run.sh --help
Traceback (most recent call last):
  File "python/run.py", line 22, in <module>
    import sling.task.download as download
ImportError: No module named download

**Comment by ringgaard** [comment]
Try to run:
```
python -c "import sys; print sys.path"
```
You should see `/home/lenyabloko/sling/python` in the list.

The weird thing is that you don't get the error on the previous line (`import sling.task.corpora as corpora`).

**Comment by lenyabloko** [comment]
No, I dont see it

$ python -c "import sys; print sys.path"                
     
['', '/usr/local/lib/python2.7/dist-packages', '/home/lenyabloko/anaconda3/envs/python2/lib/python27.zip', '/home/leny
abloko/anaconda3/envs/python2/lib/python2.7', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/plat-linux2', '/h
ome/lenyabloko/anaconda3/envs/python2/lib/python2.7/lib-tk', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/li
b-old', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/lib-dynload', '/home/lenyabloko/anaconda3/envs/python2/
lib/python2.7/site-packages']

**Comment by ringgaard** [comment]
Oh, sorry, what I meant was that one of the paths should have a sling symlink to `/home/lenyabloko/sling/python`. It looks like you don't have `/usr/local/lib/python2.7/dist-packages` in your path, so you could use this instead:
```
sudo ln -s $(realpath python) /usr/local/lib/python2.7/dist-packages/sling
```

**Comment by lenyabloko** [comment]
I set the symlink as you suggested and sys.path shows it but still get error

$ sudo ln -s /home/lenyabloko/sling/python /usr/local/li
b/python2.7/dist-packages/sling
ln: failed to create symbolic link '/usr/local/lib/python2.7/dist-packages/sling/python': File exists
(python2) lenyabloko@cloudshell:~/sling (compact-haiku-176904)$ python -c "import sys; print sys.path"
['', '/usr/local/lib/python2.7/dist-packages', '/home/lenyabloko/anaconda3/envs/python2/lib/python27.zip', '/home/leny
abloko/anaconda3/envs/python2/lib/python2.7', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/plat-linux2', '/h
ome/lenyabloko/anaconda3/envs/python2/lib/python2.7/lib-tk', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/li
b-old', '/home/lenyabloko/anaconda3/envs/python2/lib/python2.7/lib-dynload', '/home/lenyabloko/anaconda3/envs/python2/
lib/python2.7/site-packages']

**Comment by rahul1980** [comment]
Seems like the link already exists. You can try removing it and trying again:
sudo rm /usr/local/lib/python2.7/dist-packages/sling
sudo ln -s $(realpath python) /usr/local/lib/python2.7/dist-packages/sling

If this fails, please open the python interpreter, and do the following:
>>> import sling
>>> help(sling)
This will open a page. Please check what's under "FILE". You should see something like:
FILE
    /usr/local/lib/python2.7/dist-packages/sling/__init__.py

**Comment by lenyabloko** [comment]
>>>help(sling)
Help on package sling:
NAME
    sling
FILE
    /usr/local/lib/python2.7/dist-packages/sling/__init__.py
PACKAGE CONTENTS
    flags
    log
    nlp (package)
    pysling
    python (package)
    task (package)
....

**Comment by rahul1980** [comment]
Very strange, there shouldn't be "python" in your package contents. I think for some reason, there is erroneously a "python" folder inside your sling/python folder. I would suggest starting afresh, i.e. remove your sling repo, remove the soft link, checking out the caspar branch & compiling pysling.so, and re-linking to it, and then check the package contents again.

For example, here is what I get on "help(sling)":

```
Help on package sling:

NAME
    sling

FILE
    /usr/lib/python2.7/dist-packages/sling/__init__.py

PACKAGE CONTENTS
    flags
    flow
    log
    myelin (package)
    nlp (package)
    pysling
    run
    task (package)

SUBMODULES
    api

```

**Comment by lenyabloko** [comment]
HI again,
I already tried fresh couple of times. I think you hit the head of nail about the python entry.
This is what shows at the end of the page from above

HELP -- Press RETURN for more, or q when done...skipping...
drwxr-xr-x 9 lenyabloko lenyabloko 4096 Aug 10 14:26 ..
-rw-r--r-- 1 lenyabloko lenyabloko  185 Jul 19 04:16 BUILD
-rw-r--r-- 1 lenyabloko lenyabloko 2286 Jul 19 04:17 flags.py
-rw-r--r-- 1 lenyabloko lenyabloko  374 Jul 19 04:17 __init__.py
-rw-r--r-- 1 lenyabloko lenyabloko 1027 Jul 19 04:17 log.py
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 myelin
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 nlp
lrwxrwxrwx 1 lenyabloko lenyabloko   35 Jul 19 04:16 pysling.so -> ../bazel-bin/sling/pyapi/pysling.so
-rwxr-xr-x 1 lenyabloko lenyabloko 6913 Jul 19 04:17 run.py
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 task
lenyabloko@thinker:/usr/local/lib/python2.7/dist-packages/sling/python$ 

So there is no python entry on that list

Then I run the help{sling} in Anaconda python2.7 shell because my root pyhon is 3.6

lenyabloko@thinker:~/sling/python$ source activate python2.7
(python2.7) lenyabloko@thinker:~/sling/python$ ls -al
total 44
drwxr-xr-x 5 lenyabloko lenyabloko 4096 Jul 19 04:17 .
drwxr-xr-x 9 lenyabloko lenyabloko 4096 Aug 10 14:26 ..
-rw-r--r-- 1 lenyabloko lenyabloko  185 Jul 19 04:16 BUILD
-rw-r--r-- 1 lenyabloko lenyabloko 2286 Jul 19 04:17 flags.py
-rw-r--r-- 1 lenyabloko lenyabloko  374 Jul 19 04:17 __init__.py
-rw-r--r-- 1 lenyabloko lenyabloko 1027 Jul 19 04:17 log.py
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 myelin
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 nlp
lrwxrwxrwx 1 lenyabloko lenyabloko   35 Jul 19 04:16 pysling.so -> ../bazel-bin/sling/pyapi/pysling.so
-rwxr-xr-x 1 lenyabloko lenyabloko 6913 Jul 19 04:17 run.py
drwxr-xr-x 2 lenyabloko lenyabloko 4096 Jul 19 04:17 task
(python2.7) lenyabloko@thinker:~/sling/python$ export PYTHONPATH=/usr/local/lib/python2.7/dist-packages
(python2.7) lenyabloko@thinker:~/sling/python$ ./run.sh --help
-bash: ./run.sh: No such file or directory
(python2.7) lenyabloko@thinker:~/sling/python$ cd ..
(python2.7) lenyabloko@thinker:~/sling$ ./run.sh --help
Traceback (most recent call last):
  File "python/run.py", line 22, in <module>
    import sling.task.download as download
ImportError: No module named download

Still no entry for python!

Only help(slng) shows it. So may be it is due to Anaconda shell?
What do you think?

Thanks

**Comment by rahul1980** [comment]
/usr/local/lib/python2.7/dist-packages/sling should just be a soft link to ~/sling/python (or wherever your sling repo is)
So there shouldn't be anything like /usr/local/lib/python2.7/dist-packages/sling/python because that would be a link to ~/sling/python/python and no such folder exists.

Did you try removing the link and trying again:
```
sudo rm /usr/local/lib/python2.7/dist-packages/sling
cd ~/sling  (or wherever your sling repo is)
sudo ln -s "$(realpath python)" /usr/local/lib/python2.7/dist-packages/sling
```

I am not very familiar with anaconda setups, so can't comment on if/how it matters. All we want to ensure is that the default python is 2.7, and that it is picking packages from /usr/local/lib/python2.7/dist-packages, and that /usr/local/lib/python2.7/dist-packages/sling is just a link to your ~/sling/python folder.

**Comment by lenyabloko** [comment]
Ok, I did everything as you described.  Now it actually fails to import pysling

(python2.7) lenyabloko@thinker:/usr/local/lib/python2.7/dist-packages$ sudo rm -r sling
(python2.7) lenyabloko@thinker:/usr/local/lib/python2.7/dist-packages$ sudo ln -s /home/lenyabloko/sling/python /usr
/local/lib/python2.7/dist-packages/sling
(python2.7) lenyabloko@thinker:/usr/local/lib/python2.7/dist-packages$ ls -al
total 16
drwxrwsr-x 4 root staff 4096 Aug 13 21:22 .
drwxrwsr-x 4 root staff 4096 Jun 11 18:30 ..
lrwxrwxrwx 1 root staff   29 Aug 13 21:22 sling -> /home/lenyabloko/sling/python
drwxr-sr-x 2 root staff 4096 Jul 17 19:42 sling-1.0.0.dist-info
drwxr-sr-x 2 root staff 4096 Aug 13 20:07 sling-2.0.0.dist-info
(python2.7) lenyabloko@thinker:/usr/local/lib/python2.7/dist-packages$ cd \~/sling
(python2.7) lenyabloko@thinker:\~/sling$ export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/sling
(python2.7) lenyabloko@thinker:\~/sling$ ./run.sh --help
Traceback (most recent call last):
  File "python/run.py", line 18, in <module>
    import sling
ImportError: No module named sling
(python2.7) lenyabloko@thinker:\~/sling$ export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/
(python2.7) lenyabloko@thinker:\~/sling$ ./run.sh --help
Traceback (most recent call last):
  File "python/run.py", line 18, in <module>
    import sling
  File "/usr/local/lib/python2.7/dist-packages/sling/__init__.py", line 1, in <module>
    import pysling as api
ImportError: No module named pysling
(python2.7) lenyabloko@thinker:\~/sling$

**Comment by lenyabloko** [comment]
I found out why pysling is not there. Bazel failed to build it

(python2.7) lenyabloko@thinker:~/sling$ bazel build -c opt sling/pyapi:pysling.so
INFO: Analysed target //sling/pyapi:pysling.so (6 packages loaded).
INFO: Found 1 target...
ERROR: /home/lenyabloko/sling/sling/pyapi/BUILD:3:1: C++ compilation of rule '//sling/pyapi:pyapi' failed (Exit 1)
In file included from ./sling/pyapi/pydate.h:19:0,
                 from sling/pyapi/pydate.cc:15:
./sling/pyapi/pybase.h:18:30: fatal error: python2.7/Python.h: No such file or directory
 #include <python2.7/Python.h>
                              ^
compilation terminated.
Target //sling/pyapi:pysling.so failed to build

**Comment by lenyabloko** [comment]
So after I copied Python.h and all other *.h from my Anaconda env directly into ./sling/pyapi

bazel build -c opt sling/pyapi:pysling.so
INFO: Analysed target //sling/pyapi:pysling.so (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/lenyabloko/sling/sling/pyapi/BUILD:3:1: undeclared inclusion(s) in rule '//sling/pyapi:pyapi':
this rule is missing dependency declarations for the following files included by 'sling/pyapi/pyarray.cc':
  'sling/pyapi/Python.h'
  'sling/pyapi/patchlevel.h'
  'sling/pyapi/pyconfig.h'
  'sling/pyapi/pymacconfig.h'
  'sling/pyapi/pyport.h'
  'sling/pyapi/pymath.h'
  'sling/pyapi/pymem.h'
  'sling/pyapi/object.h'
  'sling/pyapi/objimpl.h'
  'sling/pyapi/pydebug.h'
  'sling/pyapi/unicodeobject.h'
  'sling/pyapi/intobject.h'
  'sling/pyapi/boolobject.h'
  'sling/pyapi/longobject.h'
  'sling/pyapi/floatobject.h'
  'sling/pyapi/complexobject.h'
  'sling/pyapi/rangeobject.h'
  'sling/pyapi/stringobject.h'
  'sling/pyapi/memoryobject.h'
  'sling/pyapi/bufferobject.h'
  'sling/pyapi/bytesobject.h'
  'sling/pyapi/bytearrayobject.h'
  'sling/pyapi/tupleobject.h'
  'sling/pyapi/listobject.h'
  'sling/pyapi/dictobject.h'
  'sling/pyapi/enumobject.h'
  'sling/pyapi/setobject.h'
  'sling/pyapi/methodobject.h'
  'sling/pyapi/moduleobject.h'
  'sling/pyapi/funcobject.h'
  'sling/pyapi/classobject.h'
  'sling/pyapi/fileobject.h'
  'sling/pyapi/cobject.h'
  'sling/pyapi/pycapsule.h'
  'sling/pyapi/traceback.h'
  'sling/pyapi/sliceobject.h'
  'sling/pyapi/cellobject.h'
  'sling/pyapi/iterobject.h'
  'sling/pyapi/genobject.h'
  'sling/pyapi/descrobject.h'
  'sling/pyapi/warnings.h'
  'sling/pyapi/weakrefobject.h'
  'sling/pyapi/codecs.h'
  'sling/pyapi/pyerrors.h'
  'sling/pyapi/pystate.h'
  'sling/pyapi/pyarena.h'
  'sling/pyapi/modsupport.h'
  'sling/pyapi/pythonrun.h'
  'sling/pyapi/ceval.h'
  'sling/pyapi/sysmodule.h'
  'sling/pyapi/intrcheck.h'
  'sling/pyapi/import.h'
  'sling/pyapi/abstract.h'
  'sling/pyapi/compile.h'
  'sling/pyapi/code.h'
  'sling/pyapi/eval.h'
  'sling/pyapi/pyctype.h'
  'sling/pyapi/pystrtod.h'
  'sling/pyapi/pystrcmp.h'
  'sling/pyapi/dtoa.h'
  'sling/pyapi/pyfpe.h'
In file included from ./sling/pyapi/Python.h:8:0,
                 from ./sling/pyapi/pybase.h:18,
                 from ./sling/pyapi/pyarray.h:19,
                 from sling/pyapi/pyarray.cc:15:
./sling/pyapi/pyconfig.h:1223:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L

In file included from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/cstdlib:41,
                 from /usr/include/c++/6/stdlib.h:36,
                 from ./sling/frame/store.h:18,
                 from ./sling/pyapi/pyarray.h:18,
                 from sling/pyapi/pyarray.cc:15:
/usr/include/features.h:225:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L

In file included from ./sling/pyapi/Python.h:8:0,
                 from ./sling/pyapi/pybase.h:18,
                 from ./sling/pyapi/pyarray.h:19,
                 from sling/pyapi/pyarray.cc:15:
./sling/pyapi/pyconfig.h:1245:0: warning: "_XOPEN_SOURCE" redefined
 #define _XOPEN_SOURCE 600

In file included from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/cstdlib:41,
                 from /usr/include/c++/6/stdlib.h:36,
                 from ./sling/frame/store.h:18,
                 from ./sling/pyapi/pyarray.h:18,
                 from sling/pyapi/pyarray.cc:15:
/usr/include/features.h:166:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700

cc1plus: warning: unrecognized command line option '-Wno-undefined-var-template'
cc1plus: warning: unrecognized command line option '-Wno-unused-command-line-argument'
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
Target //sling/pyapi:pysling.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.007s, Critical Path: 0.89s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by rahul1980** [comment]
Copying the headers like this won't work. Can you undo these copies and instead try to install them via:
`sudo apt-get install python-dev`

**Comment by lenyabloko** [comment]
Yep, that worked. Thank you.
