### ISSUE TITLE
Building SLING on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by anders-sandholm** [google/sling#296]
We currently only support Linux out-of-the-box. 

We intend to use this issue to track and document problems with building and using SLING on Windows Subsystem for Linux (WSL) and solutions for this these. 

While we do not currently intend to check these into the main code base, it can serve as a guide to those who want to use it on WSL anyway.

**Comment by anders-sandholm** [comment]
As noted in #291, on WSL you may come across an executable stack error like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sling/__init__.py", line 1, in <module>
    import pysling as api
ImportError: /usr/lib/python2.7/dist-packages/sling/pysling.so: cannot enable executable stack as shared object requires: Invalid argument
```

As also reported in #291, using the solution from https://github.com/Microsoft/WSL/issues/916#issuecomment-365898305 (i.e. `execstack -c /usr/local/lib/opencv.so*`) seems to fix the issue. Another option may be to simply disable the executable stacks using the `-z noexecstack` GCC flag.
