### ISSUE TITLE
Build Error: object of type 'ctx' has no field 'actions'

### ISSUE THREAD

**Issue by FlorianPfisterer** [google/sling#412]
OS: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-141-generic x86_64)

When trying to run the setup script (`./setup.sh`), the following error is thrown:
```
=== Install SLING dependencies
[sudo] password for florianp: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
unzip is already the newest version (6.0-20ubuntu1).
zip is already the newest version (3.0-11).
python3.5 is already the newest version (3.5.2-2ubuntu0~16.04.8).
python3.5-dev is already the newest version (3.5.2-2ubuntu0~16.04.8).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 253 not upgraded.

=== Build SLING
ERROR: /home/florianp/sling/sling/nlp/document/BUILD:210:1: in genembed rule //sling/nlp/document:corpus-app_genembed: 
Traceback (most recent call last):
	File "/home/florianp/sling/sling/nlp/document/BUILD", line 210
		genembed(name = 'corpus-app_genembed')
	File "/home/florianp/sling/tools/embed.bzl", line 10, in _genembed_impl
		ctx.actions
object of type 'ctx' has no field 'actions'.
ERROR: Analysis of target '//sling/nlp/document:corpus-app_genembed' failed; build aborted.
``` 

I couldn't find anything on this online and I'm not familiar with Bazel.
So perhaps one of you can point me in the right direction. What's the problem?

**Comment by FlorianPfisterer** [comment]
Installing bazel 0.28.0 did the trick. Thank you very much! 
(FYI: `export UPGRADE_BAZEL=1` did not)
