### ISSUE TITLE
TypeError: 'ParserState' object is not iterable

### ISSUE THREAD

**Issue by jayralencar** [google/sling#434]
Error on training SLING:

`...
[2019-11-19 13:44:03.101947] BatchLoss after (497 batches = 3976 examples): 0.1613 incl. L2=0.002289 (0.5 secs) (rss=204216)
[2019-11-19 13:44:03.861944] BatchLoss after (498 batches = 3984 examples): 0.1848 incl. L2=0.002289 (0.5 secs) (rss=204216)
[2019-11-19 13:44:04.688260] BatchLoss after (499 batches = 3992 examples): 0.1562 incl. L2=0.002289 (0.5 secs) (rss=204216)
[2019-11-19 13:44:05.609689] BatchLoss after (500 batches = 4000 examples): 0.1065 incl. L2=0.002290 (0.6 secs) (rss=204216)

Annotating dev documents [2019-11-19 13:44:05.620621] (rss=204216)
Traceback (most recent call last):
  File "sling/nlp/parser/tools/train_pytorch.py", line 99, in <module>
    train(flags.arg)
  File "sling/nlp/parser/tools/train_pytorch.py", line 93, in train
    trainer.train(train)
  File "sling/nlp/parser/trainer/trainer.py", line 310, in train
    self.process(document)
  File "sling/nlp/parser/trainer/trainer.py", line 178, in process
    self.evaluate()
  File "sling/nlp/parser/trainer/trainer.py", line 270, in evaluate
    metrics = self.evaluator(self.model)
  File "sling/nlp/parser/trainer/trainer.py", line 48, in dev_accuracy
    caspar.forward(document, train=False, debug=True)
TypeError: 'ParserState' object is not iterable`

How can I solve it?

**Comment by jayralencar** [comment]
Validating the prepared document solved this problem.
