### ISSUE TITLE
train.sh: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

### ISSUE THREAD

**Issue by mckinziebrandon** [google/sling#84]
I've gone through the README step-by-step about 4 times now and keep getting the following error upon running `./nlp/parser/tools/train.sh`:

```
Traceback (most recent call last):
  File "nlp/parser/tools/train.py", line 28, in <module>
    from convert import convert_model
  File "/home/brandon/Documents/Forge/resources/sling/nlp/parser/tools/convert.py", line 30, in <module>
    tf.load_op_library("bazel-bin/nlp/parser/trainer/sempar.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: bazel-bin/nlp/parser/trainer/sempar.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

This seems related to pywrap. I've confirmed that the file `/usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so` exists and I installed everything exactly as specified by the README (same .whl tensorflow pip install and all). Everything seems to exist in the correct locations and with the specified versions, but I get the error nonetheless. The error is unambiguously due to the `tf.load_op_library` call.

Not sure how helpful this is, but [this tensorflow issue](https://github.com/tensorflow/tensorflow/issues/1569) seems relevant. Thanks for any help!

For reference, the entire command + output:

```
./nlp/parser/tools/train.sh 
Writing command to /home/brandon/Documents/Forge/resources/sempar_ontonotes/out/command
INFO: Found 1 target...
Target //nlp/parser/trainer:generate-master-spec up-to-date:
  bazel-bin/nlp/parser/trainer/generate-master-spec
INFO: Elapsed time: 0.376s, Critical Path: 0.15s
I1109 14:26:46.558984 21875 generate-master-spec.cc:145] 1 documents processed.
I1109 14:26:46.914839 21875 generate-master-spec.cc:145] 10001 documents processed.
I1109 14:26:47.060022 21875 generate-master-spec.cc:148] Processed 14041 documents.
I1109 14:26:47.061583 21875 generate-master-spec.cc:156] Wrote action table to /home/brandon/Documents/Forge/resources/sempar_ontonotes/out/table, /home/brandon/Documents/Forge/resources/sempar_ontonotes/out/table.summary, /home/brandon/Documents/Forge/resources/sempar_ontonotes/out/table.unknown_symbols
I1109 14:26:47.062510 21875 generate-master-spec.cc:286] 1 documents processsed while building lexicons
I1109 14:26:47.286675 21875 generate-master-spec.cc:286] 10001 documents processsed while building lexicons
I1109 14:26:47.379338 21875 generate-master-spec.cc:308] 14041 documents processsed while building lexicon
I1109 14:26:47.381319 21875 generate-master-spec.cc:413] No pretrained word embeddings specified
I1109 14:26:47.381635 21875 generate-master-spec.cc:420] Wrote master spec to /home/brandon/Documents/Forge/resources/sempar_ontonotes/out/master_spec
INFO: Found 1 target...
Target //nlp/parser/tools:evaluate-frames up-to-date:
  bazel-bin/nlp/parser/tools/evaluate-frames
INFO: Elapsed time: 0.163s, Critical Path: 0.00s
INFO: Found 1 target...
Target //nlp/parser/trainer:sempar.so up-to-date:
  bazel-bin/nlp/parser/trainer/sempar.so
INFO: Elapsed time: 0.241s, Critical Path: 0.00s
Traceback (most recent call last):
  File "nlp/parser/tools/train.py", line 28, in <module>
    from convert import convert_model
  File "/home/brandon/Documents/Forge/resources/sling/nlp/parser/tools/convert.py", line 30, in <module>
    tf.load_op_library("bazel-bin/nlp/parser/trainer/sempar.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: bazel-bin/nlp/parser/trainer/sempar.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

**Comment by rahul1980** [comment]
Hmm, this seems to be a common problem when folks have gcc version >= 5 and they use a binary TF distro. Is your gcc >= 5 as well ?
Last comment [here](https://github.com/tensorflow/tensorflow/issues/10714) provides a workaround.

Can you try replacing [this line in train.sh](https://github.com/google/sling/blob/33ef067c39cf42c33228bffcf0b1bf7693e342ca/nlp/parser/tools/train.sh#L229) with the following:
bazel build -c opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" nlp/parser/trainer:sempar.so

**Comment by mckinziebrandon** [comment]
Ah, interesting. Yes, I'm using gcc 5.4.0. Your suggestion appears to have worked!! Thanks so much. 

That's interesting, because I tried doing that via placing
```
copts = ["D_GLIBCC_USE_CXX11_ABI=0"]
```
which didn't fix the problem, but I guess that just shows I need to study bazel a bit more. Thanks again!

**Comment by rahul1980** [comment]
Glad that worked!
Bazel is a little bit of mystery to me too :)
Closing this issue for now.
